
CREATE SEQUENCE secuencia_BP
START WITH 1
INCREMENT BY 1
MAXVALUE 1000;


CREATE SEQUENCE secuencia_BS
START WITH 1
INCREMENT BY 1
MAXVALUE 1000;


CREATE SEQUENCE secuenciaCliente
START WITH 1
INCREMENT BY 1
MAXVALUE 1000;

CREATE SEQUENCE secuenciaEmpleado
START WITH 1
INCREMENT BY 1
MAXVALUE 1000;

CREATE SEQUENCE secuenciaHC
START WITH 1
INCREMENT BY 1
MAXVALUE 1000;


CREATE SEQUENCE secuenciaProducto
START WITH 1
INCREMENT BY 1
MAXVALUE 1000;


CREATE SEQUENCE secuenciaPV
START WITH 1
INCREMENT BY 1
MAXVALUE 1000;

CREATE SEQUENCE secuenciaProvedor
START WITH 1
INCREMENT BY 1
MAXVALUE 1000;

CREATE SEQUENCE secuenciVenta
START WITH 1
INCREMENT BY 1
MAXVALUE 1000;
